name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Generate code coverage 
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v6
    - uses: SwiftyLab/setup-swift@latest
    
    - name: Run tests
      run: swift test --enable-code-coverage

    - name: Export Coverage files
      run: xcrun llvm-cov export --format=lcov .build/debug/swift-semverPackageTests.xctest/Contents/MacOS/swift-semverPackageTests -instr-profile=.build/debug/codecov/default.profdata > codecov.lcov


    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
          directory: ./.build/
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)