name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Generate code coverage 
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v6
    - uses: SwiftyLab/setup-swift@latest
    
    - name: Run tests
      run: swift test --enable-code-coverage --verbose

    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
          directory: ./.build/debug/codecov/
          files: ./.build/debug/codecov/default.profdata, ./.build/debug/codecov/swift-semver.json
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)